version: '3.7'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - .:/var/www/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app


  app:
    build:
      dockerfile: docker/php-dev.Dockerfile
      context: .
    volumes:
      - .:/var/www/app
    expose:
      - 9000
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      COMPOSER_ALLOW_SUPERUSER: 1
      APP_ENV: 'dev'

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: slim_project
      MYSQL_USER: webmaster
      MYSQL_PASSWORD: webmaster

